### ISSUE TITLE
INFOGRAFÍA: GESTIÓN DE PROYECTOS DE SOFTWARE

### ISSUE THREAD

**Issue by Rmz-Rigo** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Rigoberto2001#2]
[INFOGRAFIA_GESTPROSOFT_RIGOBERTORAMÍREZNICOLÁS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Rigoberto2001/files/9418923/INFOGRAFIA_GESTPROSOFT_RIGOBERTORAMIREZNICOLAS.pdf)

**Comment by DuilioAquino10** [comment]
Calificación 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
